### ISSUE TITLE
https://github.com/volantis-x/examples/issues

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/examples#1]
```yaml
title: 网站标题
screenshot: https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/052.jpg
description: 描述
```
